### ISSUE TITLE
密钥登录是别人的信息

### ISSUE THREAD

**Issue by krislq** [eoecn/android-app#14]
我这边想在客户端登录一下，说是需要去博客里面生成一个密钥 。我也去pc上面生成了，然后在eoe客户端中辛苦的输入一段“乱码”，结果发现是别人的信息。
1.“乱码”，用户输入太烦了，弄成二维码？扫描一下？
2.有弄密码这个过程，还不如直接用户名密码呢。
#3.登录后能干 嘛？

期待登录，获取到用户的信息，并且 与活动打通。然后我们做一个签到的功能 。

**Comment by IceskYsl** [comment]
用token的目的是不想在这个过程中传输用户名和密码，最好的方式就是整个二维码啥的扫描下，但在单为了登陆增加二维码就有点划不来，如果统一规划后，比如签到用，那可以好好规划下这个功能～

发现是别人的信息需要稍微详细一点的信息，看看是不是bug～

**Comment by krislq** [comment]
ok .好的。签到这东西，真心可以有一个。到时候morelap团队可以跟进。。

**Comment by IceskYsl** [comment]
现在这个版本加入了扫描二维码登录了。
