### ISSUE TITLE
注册时间不对!

### ISSUE THREAD

**Issue by krislq** [eoecn/android-app#16]
手机上面登录显示的是2012年,而我在社区里面显示的是2009年
![regist_time](https://f.cloud.github.com/assets/861095/434329/081ece74-af35-11e2-8e6f-033f85d6a616.jpg)
![regist_time_on_web](https://f.cloud.github.com/assets/861095/434330/0ef1e876-af35-11e2-8d9a-8192ec935661.jpg)

**Comment by krislq** [comment]
这个是服务器返回时间不对.

![registtime](https://f.cloud.github.com/assets/861095/434359/4508176c-af37-11e2-8359-9cd651de8e22.png)

**Comment by IceskYsl** [comment]
ok，是个bug。

**Comment by krislq** [comment]
本来想找个bug做个简单的pull request的.结果都不是客户端的.杯具

**Comment by IceskYsl** [comment]
是的，已提交修复。

**Comment by IceskYsl** [comment]
e币那个反了的是。

－姚尚朗（Iceskysl)

在 2013-4-27，下午8:39，"Kris.lee" notifications@github.com 写道：

本来想找个bug做个简单的pull request的.结果都不是客户端的.杯具

—
Reply to this email directly or view it on
GitHubhttps://github.com/eoecn/android-app/issues/16#issuecomment-17115512
.

**Comment by krislq** [comment]
e币,那我我这边显示是正确的啊.

**Comment by IceskYsl** [comment]
哦，那应该是后来修改了一版。

**Comment by IceskYsl** [comment]
注册时就不对的是服务器端的，服务器端做修改~

**Comment by mjkohoh** [comment]
这个issue好像已经得到解决了，要不关了它？

**Comment by IceskYsl** [comment]
服务器端已经改了，close 掉~
