### ISSUE TITLE
e币和e望反了

### ISSUE THREAD

**Issue by IceskYsl** [eoecn/android-app#2]
看看是接口给反了还是客户端用反了～

**Comment by mingxv2012** [comment]
接口没反,我自己搞反了.

9698542

发件人： IceskYsl
发送时间： 2013-03-20 17:38
收件人： eoecn/android-app
抄送： mingxv2012
主题： [android-app] e币和e望反了 (#2)
看看是接口给反了还是客户端用反了～

**Comment by IceskYsl** [comment]
这个已经修复好了～
