### ISSUE TITLE
是否在线

### ISSUE THREAD

**Issue by happydeerlet** [eoecn/android-app#25]
在线到无线：文章列表进去后显示null，是否给个提示会更好
无线到在线：无线时列表页显示连接错误，是否可以在改为在线的时候自动刷新一次

**Comment by IceskYsl** [comment]
收到。

**Comment by mjkohoh** [comment]
呃，好吧由于之前不知道可以通过fixed#xxxx关键字关联到这个issue。
所以不管怎么样原谅我吧。
关于这个issue已经提交了修改了
所以我想可以close#25了

**Comment by mjkohoh** [comment]
呃，我已经在 #86 中修复了这个bug。所以麻烦 @IceskYsl 可以关闭这个issue了

**Comment by IceskYsl** [comment]
√
