### ISSUE TITLE
绑定秘钥输入

### ISSUE THREAD

**Issue by yeungeek** [eoecn/android-app#27]
现在输入秘钥，有点麻烦
是否有考虑使用二维码扫描呢，客户端的我来支持
设置页面的二维码生成，通过网站来生成

**Comment by IceskYsl** [comment]
哇，看来这个原来设计的功能有被摆上日程的可能性啦～

**Comment by IceskYsl** [comment]
这个业务逻辑比较简单

1.在个人中心里生成一个二维码（二维码里包含这个密钥）
2.手机端扫描这个二维码，解析出密钥
3. 拿这个密钥去服务器端验证和获取用户信息

**Comment by yeungeek** [comment]
是呢，客户端的扫描目前有稳定的开源项目，zxing，整合很方便
二维码扫描，后期也会有其他用途

**Comment by IceskYsl** [comment]
@yeungeek 对，昨天 kris也说到了这个case，以后可以用来扫描线下活动签到等

**Comment by yeungeek** [comment]
刚才把所有的issue看了一遍，原来早前有人已经提议了
看来得赶紧支持了，哈哈

**Comment by vincent4j** [comment]
同城会签到，我开始澎湃啦。@kris1987 上议程啦。。。。。

**Comment by IceskYsl** [comment]
这个可以做为下一个版本里的功能了〜
我可以推进服务器端展示二维码〜

**Comment by yeungeek** [comment]
@IceskYsl, 很期待啊
服务端的roadmap，客户端已经forked

**Comment by IceskYsl** [comment]
我擦，这么速度〜

**Comment by IceskYsl** [comment]
@yeungeek 今天我在web端加上这个功能～

**Comment by yeungeek** [comment]
@IceskYsl  啊，这么速度，刚才是说我刚把项目fork过来
那现在得加油了

**Comment by yeungeek** [comment]
那我得下班后，加加班了，客户端扫描搞定它

**Comment by IceskYsl** [comment]
好，期待。
