### ISSUE TITLE
写个多人协作和参与的标准规范

### ISSUE THREAD

**Issue by IceskYsl** [eoecn/android-app#28]
我大概列下大纲，如下

包括如何fork，修改，push 到自己的repo，给eoecn发pull request，本地添加eoecn的源，fetch eoecn最新的代码，merge到自己的代码

**Comment by jiangminglu** [comment]
可以。。。我一直都是用的svn，git都是用来down 源码

**Comment by IceskYsl** [comment]
参考
https://help.github.com/articles/fork-a-repo

**Comment by IceskYsl** [comment]
我写了一份，地址在这里
http://my.eoe.cn/iceskysl/archive/3195.html
