### ISSUE TITLE
在intelliJ下编译无法通过

### ISSUE THREAD

**Issue by skywalkerlw** [eoecn/android-app#37]
这个文件无法通过编译：source/src/cn/eoe/app/widget/XListView.java

具体信息如下：（Using javac 1.7.0_21 to compile java sources）

error1: java: illegal character: \65279
error2: java: class, interface, or enum expected

**Comment by feicien** [comment]
使用intelliJ开发Android怎么样，和eclipse相比，有那些优点？

**Comment by IceskYsl** [comment]
看上去是字符编码导致的。

**Comment by IceskYsl** [comment]
不用intelliJ，希望有用intelliJ的同学具体查一下〜
