### ISSUE TITLE
文件编码非utf-8导致乱码

### ISSUE THREAD

**Issue by addcn** [eoecn/android-app#38]
source\src\cn\eoe\app\utils\DateUtil.java文件编码非utf-8导致乱码

**Comment by IceskYsl** [comment]
可以修复下提个pull　request〜

**Comment by fatsoon** [comment]
锟斤拷问题啊，纠结。。

**Comment by fatsoon** [comment]
到底怎么解决啊

**Comment by rockybean** [comment]
我这边碰到XListView.java里面utf-8带bom出现编译错误，但没有碰到乱码问题

**Comment by fatsoon** [comment]
应该是gbk转utf8出现了错误，导致不可逆吧
