### ISSUE TITLE
登录接口存在返回空值问题

### ISSUE THREAD

**Issue by lichen228** [eoecn/android-app#46]
扫描个人主页中的二维码登录，存在返回空值现象

***_成功**_*
二维码信息：
http://weixin.qq.com/r/7HX_8R7EfiABhw_SnyDI
请求：
http://api.eoe.cn/client/userinfo?key=http://weixin.qq.com/r/7HX_8R7EfiABhw_SnyDI&uid=//weixin.qq.com/r/7HX_8R7EfiABhw_SnyDI&nonce=9e49871c46&timestamp=1367550802876&api_sign=8bf2964ef164781d02f1b39b7010989c
返回：
{"response":{"info":{"name":"lichen228","eoe_p":"1","eoe_m":"29","head_image_url":"http:\/\/www.eoeandroid.com\/uc_server\/avatar.php?uid=943006&size=small","reg_at":"2013-05-02 10:39:37","icon":[{"name":"\u4e00\u7ea7\u52cb\u7ae0","img":"http:\/\/www.eoeandroid.com\/static\/image\/common\/001.png"}]},"favorite":[{"name":"\u535a\u5ba2\u6536\u85cf","lists":[{"title":"\u57fa\u4e8eGithub\u53c2\u4e0eeoe\u7684\u5f00\u6e90\u9879\u76ee\u6307\u5357","short_content":"Github\u662f\u4e00\u4e2a\u975e\u5e38\u68d2\u7684\u9879\u76ee\u6258\u7ba1\u7f51\u7ad9\uff0c\u57fa\u4e8eGi...","url":"http:\/\/api.eoe.cn\/client\/blog?k=show&id=3195"}]},{"name":"\u8d44\u8baf\u6536\u85cf","lists":[]}]}}

***_失败**_*
二维码信息：
http://weixin.qq.com/r/7HX_8R7EfiABhw_SnyDI
请求:
http://api.eoe.cn/client/userinfo?key=http://weixin.qq.com/r/7HX_8R7EfiABhw_SnyDI&uid=//weixin.qq.com/r/7HX_8R7EfiABhw_SnyDI&nonce=6e47812517&timestamp=1367557007593&api_sign=68a9b6995db8cd67bdfef336cbcf8ee8
返回:
{"response":{"info":{"name":null,"eoe_p":0,"eoe_m":0,"head_image_url":"http:\/\/www.eoeandroid.com\/uc_server\/avatar.php?uid=&size=small","reg_at":"1970-01-01 08:00:00","icon":[]},"favorite":[{"name":"\u535a\u5ba2\u6536\u85cf","lists":[]},{"name":"\u8d44\u8baf\u6536\u85cf","lists":[]}]}}

![eoe](https://f.cloud.github.com/assets/4326872/469227/8caf7754-b6b7-11e2-948f-4fb9ff1586d7.png)

**Comment by IceskYsl** [comment]
不大对呢，不是首页的二维码，是个人资料的的那个二维码～

**Comment by IceskYsl** [comment]
后台首页那个二维码太干扰肋～等下把那个地方拿下～

**Comment by feicien** [comment]
只有我的二维码图片显示不了吗？
我用的chrome浏览器
生成的图片链接如下：
http://a1.eoe.cn/wwwhttp://a1.eoe.cn/qrcode/201303/21/13aa/e6eb8b09df906096fb6f1345cc017e91.png

**Comment by lichen228** [comment]
密钥管理里的那个二维码是可以的。
我的问题主要在于为什么我扫描了不对的二维码，要么通过了返回空值，要么返回了正确的信息呢？
返回空值可以改代码提示登录失败然后注销登录
返回正确信息的原因我不太明白，是已经存在用户token没过期吗？这个需要请教下

**Comment by feicien** [comment]
我点击获取新秘钥，二维码又出来了

**Comment by yeungeek** [comment]
@lichen228 ,这个问题我也遇到了，而且使用其他的规律账号可以登录
[API接口文档](https://github.com/eoecn/android-app/wiki/API%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)

@IceskYsl ,获取用户信息接口问题很大，开始我测试了增加判断返回的name是否为空
没有想到，我用有规律的账号，居然返回了admin账号，太不安全了

**Comment by IceskYsl** [comment]
@yeungeek 收到了，马上检查～ 多谢～

**Comment by IceskYsl** [comment]
紧急修复了，谢谢以上各位大大～

{"response":{"isErr":1,"msg":"\u5bc6\u94a5\u9519\u8bef\uff01"}}
