### ISSUE TITLE
SlidingMenu拉伸动画

### ISSUE THREAD

**Issue by IceskYsl** [eoecn/android-app#5]
from：4j
对客户端也来吐槽吧，最郁闷的是，Slidebar的跳转，居然SlideBar本身还拉伸的，这样就相当于又2个动画，咋眼。

**Comment by IceskYsl** [comment]
这个问题你提交的，你得闲可以修改下～哈哈～

**Comment by vincent4j** [comment]
好吧，你连着错别字一同复制过来了——“又2个动画”。
