### ISSUE TITLE
点进文章有时候出现NULL字样

### ISSUE THREAD

**Issue by gdchaochao** [eoecn/android-app#55]
4.1.1上试用了一下。发现有时候点进博客，不知道是网络原因还是其他什么问题，出现NULL字样。是不是可以加些判断检测呢。另外，收藏评论也一直不成功，是还没做好吧

**Comment by mjkohoh** [comment]
呃，好吧由于之前不知道可以通过fixed#xxxx关键字关联到这个issue。
所以不管怎么样原谅我吧。
关于这个issue已经提交了修改了
所以我想可以close#52了

**Comment by mjkohoh** [comment]
呃，我已经在 #86 中修复了这个bug。所以麻烦 @IceskYsl 可以关闭这个issue了

**Comment by IceskYsl** [comment]
√
