### ISSUE TITLE
WARNING: Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by ghost** [eoecn/android-app#59]
本应用，好像登录不验证CSRF token。如果使用，如何解决WARNING: Can't verify CSRF token authenticity错误？有遇到的吗？网上的很多解决方案都是在服务器端禁用token验证。

**Comment by ghost** [comment]
我的处理是：首先确保启用cookie成功，其次是模仿浏览器：给httpClient客户端添加head信息csrf-token；在传给post方法的参数中添加csrf-token参数。似乎可以了，但不清楚为什么？

**Comment by IceskYsl** [comment]
去掉服务器端关于CSRF的验证咯～
