### ISSUE TITLE
突然运行出现的问题：could not find class 'cn.eoe.app.ui.MainActivity'

### ISSUE THREAD

**Issue by whgreate** [eoecn/android-app#60]
![qq20130516190147](https://f.cloud.github.com/assets/811644/512051/585942b0-be18-11e2-80dd-4b2ef2fc2bd0.png)

以前还好好的，今天运行突然就蹦出这个错误，请问怎么搞的，也就是找不到类的问题，没动过呀

**Comment by vincent4j** [comment]
这样问问题，没法解答e，读不明白。

在 2013年5月16日星期四，whgreate 写道：

> [image: qq20130516190147]https://f.cloud.github.com/assets/811644/512051/585942b0-be18-11e2-80dd-4b2ef2fc2bd0.png
> 
> 以前还好好的，今天运行突然就蹦出这个错误，请问怎么搞的，也就是找不到类的问题，没动过呀
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eoecn/android-app/issues/60
> .

## 

Best Regards;
Vincent 4J http://about.me/vincent4j

**Comment by IceskYsl** [comment]
@whgreate 解决了？

**Comment by whgreate** [comment]
嗯，重启了eclips就okl了

------------------ 原始邮件 ------------------
发件人: "IceskYsl"notifications@github.com;
发送时间: 2013年5月17日(星期五) 上午9:27
收件人: "eoecn/android-app"android-app@noreply.github.com; 
抄送: "whgreate"624906158@qq.com; 
主题: Re: [android-app] 突然运行出现的问题：could not find class 'cn.eoe.app.ui.MainActivity' (#60)

@whgreate 解决了？
