### ISSUE TITLE
工程导入问题，工程导入后提示找不到gen文件夹，新建一个gen文件夹之后，很多代码报错看了下都是找不到项目R文件，其实也就是GEN文件夹下什么都没生成，求解决方案

### ISSUE THREAD

**Issue by hunterxman** [eoecn/android-app#62]

**Comment by vincent4j** [comment]
不能直接通过“import”导入，需通过 new 》 Android 》Android Project from Existing Code 导入，截图如下：
![new](https://f.cloud.github.com/assets/808989/539663/cbe55dbc-c1c0-11e2-849f-d0093b58d643.png)

@hunterxman 试下，看能不能解决你的问题。不行的话，再留言。

**Comment by IceskYsl** [comment]
@vincent4j  √

**Comment by hunterxman** [comment]
还是不行额，project from existing code 还是那样的，GEN文件夹这次不用自己建了，但是下面还是什么都没有，代码报错还是找不到 [[[import cn.eoe.app.R;]]]

**Comment by vincent4j** [comment]
@hunterxman  build，或者 clean 一下就好了。
![clean](https://f.cloud.github.com/assets/808989/539704/28b7f03e-c1c3-11e2-8572-17ba45b0d4a7.png)

**Comment by hunterxman** [comment]
我最开始就是CLEAN的，没用，V4你在吗
QQ上说说把

**Comment by hunterxman** [comment]
我QQ 906162426

**Comment by IceskYsl** [comment]
@hunterxman 要是解决了，可以来更新下～

**Comment by hunterxman** [comment]
没解决啊，v4都跟我远程了还是不行，应该是我的环境问题，我的工程发给v4是可以的，我自己机器虾不行

**Comment by vincent4j** [comment]
我不叫v4，亲。

在 2013年5月22日星期三，hunterxman 写道：

> 没解决啊，v4都跟我远程了还是不行，应该是我的环境问题，我的工程发给v4是可以的，我自己机器虾不行
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eoecn/android-app/issues/62#issuecomment-18252151
> .

## 

Best Regards;
Vincent 4J http://about.me/vincent4j

**Comment by KennethYo** [comment]
亲，你试试这个http://my.eoe.cn/786272/archive/3937.html 有帮助吗

游子聪的QQ邮箱

发件人： Vincent 4J
发送时间： 2013-05-22 09:22
收件人： eoecn/android-app
主题： Re: [android-app] 工程导入问题，工程导入后提示找不到gen文件夹，新建一个gen文件夹之后，很多代码报错看了下都是找不到项目R文件，其实也就是GEN文件夹下什么都没生成，求解决方案 (#62)
我不叫v4，亲。 

在 2013年5月22日星期三，hunterxman 写道： 

> 没解决啊，v4都跟我远程了还是不行，应该是我的环境问题，我的工程发给v4是可以的，我自己机器虾不行 
> 
> — 
> Reply to this email directly or view it on GitHubhttps://github.com/eoecn/android-app/issues/62#issuecomment-18252151 
> . 

## 

Best Regards; 
Vincent 4J http://about.me/vincent4j

**Comment by hunterxman** [comment]
非常感谢KEnnethyo同学提供的链接，按照他的做法解决了，的确是我装android studio 更新过sdk但是sdk 相应的tools没更新，然后我把tools 和 android support library更新一下就好了，这个项目推荐用android 4.0的sdk，我试过用2.3的话某些布局属性会报错，但是看了下去掉那些属性也没关系。

**Comment by IceskYsl** [comment]
哎呀，不容易，你可以去写个博客介绍介绍这个基础又诡异的问题了～

**Comment by vincent4j** [comment]
涨见识了，22居然多出个：Android SDK Build-tools
看 @futurexiong 的blog才知道。

**Comment by KennethYo** [comment]
给hunterxman回复的链接就是我在eoe上的博文，写完博文才看到eoe主页上推荐的futurexiong的博文要比我写的精彩，并且图文并茂。

------------------ 原始邮件 ------------------
发件人: "IceskYsl"notifications@github.com;
发送时间: 2013年5月22日(星期三) 上午10:54
收件人: "eoecn/android-app"android-app@noreply.github.com; 
抄送: "KennethYo"youzicong@qq.com; 
主题: Re: [android-app] 工程导入问题，工程导入后提示找不到gen文件夹，新建一个gen文件夹之后，很多代码报错看了下都是找不到项目R文件，其实也就是GEN文件夹下什么都没生成，求解决方案 (#62)

哎呀，不容易，你可以去写个博客介绍介绍这个基础又诡异的问题了～

**Comment by yeungeek** [comment]
我前两天也遇到类似情况了，adt22升级后，出现java.lang.ClassNotFoundException的错误
倒不是没有生成R文件，而是在bin下的dexedLibs没有对应的依赖jar生成(第三方的)
刚才看了@futurexiong的blog，两种问题都可以解决，更新速度很快啊，学习ing

**Comment by mjkohoh** [comment]
@IceskYsl  要不关闭这个issus？

**Comment by IceskYsl** [comment]
关掉了，遇到类似问题，请参考
@futurexiong的blog
