### ISSUE TITLE
最新版源码导入eclipse编译安装打开报错

### ISSUE THREAD

**Issue by yankunren** [eoecn/android-app#71]
最新版源码导入eclipse编译安装报错

**Comment by IceskYsl** [comment]
贴log〜谢谢

**Comment by yankunren** [comment]
05-30 10:22:43.720: E/AndroidRuntime(6696): FATAL EXCEPTION: main
05-30 10:22:43.720: E/AndroidRuntime(6696): java.lang.NullPointerException
05-30 10:22:43.720: E/AndroidRuntime(6696):     at cn.eoe.app.utils.ImageUtil.getExternalCacheDir(ImageUtil.java:90)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at cn.eoe.app.utils.ImageUtil.setThumbnailView(ImageUtil.java:65)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at cn.eoe.app.view.BlogFragment$MyAdapter.getView(BlogFragment.java:159)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.AbsListView.obtainView(AbsListView.java:2047)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.ListView.makeAndAddView(ListView.java:1772)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.ListView.fillDown(ListView.java:672)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.ListView.fillFromTop(ListView.java:732)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.ListView.layoutChildren(ListView.java:1611)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.AbsListView.onLayout(AbsListView.java:1877)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.View.layout(View.java:11288)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewGroup.layout(ViewGroup.java:4224)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.View.layout(View.java:11288)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewGroup.layout(ViewGroup.java:4224)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1520)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.View.layout(View.java:11288)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewGroup.layout(ViewGroup.java:4224)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1629)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1487)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.LinearLayout.onLayout(LinearLayout.java:1400)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.View.layout(View.java:11288)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewGroup.layout(ViewGroup.java:4224)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.View.layout(View.java:11288)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewGroup.layout(ViewGroup.java:4224)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1629)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1487)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.LinearLayout.onLayout(LinearLayout.java:1400)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.View.layout(View.java:11288)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewGroup.layout(ViewGroup.java:4224)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.View.layout(View.java:11288)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewGroup.layout(ViewGroup.java:4224)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1494)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2447)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.os.Handler.dispatchMessage(Handler.java:99)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.os.Looper.loop(Looper.java:137)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at android.app.ActivityThread.main(ActivityThread.java:4439)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at java.lang.reflect.Method.invokeNative(Native Method)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at java.lang.reflect.Method.invoke(Method.java:511)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
05-30 10:22:43.720: E/AndroidRuntime(6696):     at dalvik.system.NativeStart.main(Native Method)

**Comment by yankunren** [comment]
估计对无SD卡的情况 ，没有处理好

**Comment by mjkohoh** [comment]
我想这个issue已经在 #74 中得到解决了。所以关闭这个issue吧 @IceskYsl 

---

好吧，另外我错了，这个issue和 issue79和issue78没有关系。我错误的引用了，但是我现在不知道该怎么取消这2个引用了。

**Comment by IceskYsl** [comment]
@KOHOH1992 引用好像 del 不掉~

**Comment by mjkohoh** [comment]
这个issue应该是在 #74中得到解决了。所以我建议关掉它。 @IceskYsl  原谅我的强迫症

**Comment by IceskYsl** [comment]
√
