### ISSUE TITLE
java.lang.NoClassDefFoundError: com.umeng.analytics.MobclickAgent

### ISSUE THREAD

**Issue by HeroKince** [eoecn/android-app#77]
运行出现这个错误java.lang.NoClassDefFoundError: com.umeng.analytics.MobclickAgent

**Comment by wy353208214** [comment]
同问

**Comment by KennethYo** [comment]
打包运行前的时候，看看这里有没有没被选中。初步推测Umeng SDK 没有被打包进去。

游子聪的QQ邮箱

From: wy353208214
Date: 2013-06-18 13:52
To: eoecn/android-app
Subject: Re: [android-app] java.lang.NoClassDefFoundError: com.umeng.analytics.MobclickAgent (#77)
同问

**Comment by wy353208214** [comment]
已经正常了，可能是eclipse的问题，看似导入umeng实则没有导入，手动再倒入下umeng jar包就可以了，感谢楼上的回复！

**Comment by caoyi01** [comment]
我手动导入了，为什么还报这个错误？？

**Comment by t-gao** [comment]
很可能是方法数超限的问题，你把你的apk解压开看看是不是有两个dex？若是的话，打开multidex支持就可以了
