### ISSUE TITLE
add a  scan line  ?

### ISSUE THREAD

**Issue by janrone** [eoecn/android-app#80]

**Comment by mjkohoh** [comment]
非常疑惑，janrone同学，你到底想要表达什么？

**Comment by IceskYsl** [comment]
@KOHOH1992 看上去是测试~

**Comment by janrone** [comment]
像微信那样 扫瞄二维码有一条线  @KOHOH1992

**Comment by feicien** [comment]
要不，我来加上？

**Comment by janrone** [comment]
怎么加呢，可以上下动的 @feicien

**Comment by ghost** [comment]
好的，那谢谢你了。程辉 编写：>要不，我来加上？

**Comment by feicien** [comment]
代码已经提交了
在 2013年9月9日 下午12:02，"农药" notifications@github.com写道：
