### ISSUE TITLE
在4.0以上的系统，slidingmenu会变得卡和闪，请问有什么解决方案

### ISSUE THREAD

**Issue by bboyayan** [eoecn/android-app#84]

**Comment by mjkohoh** [comment]
你确定？难道是特例。能描述一下你的机型和系统版本吗?

**Comment by bboyayan** [comment]
嗯，我测试了三台机器，包括mx2,sony,ztc。系统均是4.1版本

ayanwork

发件人： KOHOH
发送时间： 2013-09-03 16:58
收件人： eoecn/android-app
抄送： bboyayan
主题： Re: [android-app] 在4.0以上的系统，slidingmenu会变得卡和闪，请问有什么解决方案 (#84)
你确定？难道是特例。能描述一下你的机型和系统版本吗?

**Comment by mjkohoh** [comment]
好吧，中间出了点意外，忘记这个issue了。
不过经过测试的确有这种现象。
有没有哪位同学能够帮助解决的，哪怕是指点下，给点思路也可以吗！
鄙人比较菜，还没有一点思路
不管怎么样，还是会不断尝试去解决这个issue的。
@IceskYsl  @com360

**Comment by IceskYsl** [comment]
卡这个问题确实存在~

**Comment by zmywly8866** [comment]
是不是把硬件加速关掉了？

在 2013-09-10 22:39:05，IceskYsl notifications@github.com 写道：

卡这个问题确实存在~

**Comment by mjkohoh** [comment]
的确是因为把硬解加速关掉的原因。我把MainActivity的硬件加速开启后，卡顿的现象就消失了。
另外想请教一下@IceskYsl，为什么eoe里面用到的其他开源项目没有使用常用的依赖方式，而是直接把代码包含在了eoe项目中？我总觉得这样做让项目很混乱。
非常感谢@zmywly8866，虽然一开始没有照你提示的方向去解决这个issue，直到最后因为意外误打误撞找到原因（一直以为一定不是硬件加速的原因，我好愚蠢）。

**Comment by zmywly8866** [comment]
关于直接把代码包含在了eoe项目中问题，我觉得是为了是方便下载源码的人，只需要下载一个附件就可以正常使用整个工程，省去down或者找依赖工程的麻烦。

在 2013-09-27 22:47:29，KOHOH notifications@github.com 写道：

的确是因为把硬解加速关掉的原因。我把MainActivity的硬件加速开启后，卡顿的现象就消失了。
另外想请教一下@IceskYsl，为什么eoe里面用到的其他开源项目没有使用常用的依赖方式，而是直接把代码包含在了eoe项目中？我总觉得这样做让项目很混乱。
非常感谢@zmywly8866，虽然一开始没有照你提示的方向去解决这个issue，直到最后因为意外误打误撞找到原因（一直以为一定不是硬件加速的原因，我好愚蠢）。

**Comment by mjkohoh** [comment]
这里问一下 @IceskYsl 。我对于这个issue的修改是不是需要单独做一个request。虽然我参加这个项目有一段时间了，但是对于具体如何协同参与这个项目我还是不太了解。因此我很疑惑是不是需要单独做一个request。

**Comment by IceskYsl** [comment]
@KOHOH1992 pull 按照功能来切分，如果多个 issue 是类似问题，那么久可以合在一起来解决和 pull~
