### ISSUE TITLE
登录用用户名和密码登录不成功？

### ISSUE THREAD

**Issue by dzwillpower** [eoecn/android-app#85]
登录用用户名和密码登录不成功？

**Comment by mjkohoh** [comment]
能具体描述一下吗？

**Comment by mjkohoh** [comment]
@dzwillpower 同学。我当真是没有办法重现你所说的情况。可能是你提供的信息不够详细的原因吧。 @IceskYsl 我想如果没有更多类似情况，这个issue可以被关闭了。

**Comment by IceskYsl** [comment]
没抓到具体的 case，先 close 掉了~
